export type SSEEventType =
  | 'chat:token'
  | 'chat:done'
  | 'chat:message'
  | 'chat:tool-call-start'
  | 'chat:tool-call'
  | 'chat:tool-result'
  | 'task:status'
  | 'task:done'
  | 'task:deleted'
  | 'cron:triggered'
  | 'cron:created'
  | 'cron:updated'
  | 'cron:deleted'
  | 'queue:update'
  | 'kin:error'
  | 'kin:created'
  | 'kin:updated'
  | 'kin:deleted'
  | 'prompt:pending'
  | 'prompt:answered'
  | 'webhook:created'
  | 'webhook:updated'
  | 'webhook:deleted'
  | 'webhook:triggered'
  | 'compacting:start'
  | 'compacting:done'
  | 'channel:created'
  | 'channel:updated'
  | 'channel:deleted'
  | 'channel:message-received'
  | 'channel:message-sent'
  | 'channel:user-pending'
  | 'channel:user-approved'
  | 'notification:new'
  | 'notification:read'
  | 'notification:read-all'
  | 'connected'

export interface SSEEvent {
  type: SSEEventType
  kinId?: string
  data: Record<string, unknown>
}
